# Generated by Django 5.2.17 on 2026-09-03 11:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(help_text='Used by the agent at the destination to arrange handover.', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, for example +599 9 123 4567.', regex='^\\+?[\\d\\s()-]{7,20}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Optional name for this address, such as "Home" or "Office".', max_length=50)),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('CW', 'Curaçao'), ('BQ', 'Bonaire'), ('AW', 'Aruba'), ('SX', 'Sint Maarten'), ('SR', 'Suriname'), ('NL', 'Nederland')], default='CW', max_length=2)),
                ('is_default', models.BooleanField(default=False, help_text='Pre-filled when this customer places an order.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'ordering': ['-is_default', 'city'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('quoted', 'Quote sent'), ('paid', 'Paid'), ('purchased', 'Products purchased'), ('in_transit', 'In transit'), ('arrived', 'Arrived at destination'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='quoted', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('value_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='accounts.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_user'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['user', 'status'], name='accounts_pa_user_id_eb93f2_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['tracking_number'], name='accounts_pa_trackin_8f412c_idx'),
        ),
    ]
