# Generated by Django 5.2.17 on 2026-09-03 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='delivery_address_text',
            field=models.TextField(blank=True, help_text='Snapshot of the delivery address as it was when shipped.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='accounts.address'),
        ),
    ]
