# Generated by Django 5.2.17 on 2026-09-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_package_delivery_address_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anonymised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_offers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_shipping',
            field=models.BooleanField(default=True),
        ),
    ]
