# Generated by Django 5.2.17 on 2026-09-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_anonymised_at_user_notify_newsletter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='estimated_arrival',
            field=models.DateField(blank=True, help_text='Shown on the public tracking page. Leave empty if not known yet.', null=True),
        ),
    ]
