# Generated by Django 5.2.17 on 2026-09-08 09:13

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_package_estimated_arrival'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'Receipt'), ('invoice', 'Shop invoice'), ('customs', 'Customs form'), ('other', 'Other')], default='receipt', max_length=20)),
                ('file', models.FileField(upload_to=accounts.models.package_document_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.package')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['package', '-created_at'], name='accounts_pa_package_ef9520_idx')],
            },
        ),
    ]
