# Generated by Django 5.2.17 on 2026-09-08 12:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_packagedocument_optional_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('status_changed', 'Shipment status changed'), ('invoice_raised', 'Invoice raised'), ('invoice_resubmitted', 'Invoice resubmitted'), ('invoice_approved', 'Invoice approved'), ('invoice_rejected', 'Invoice rejected'), ('invoice_sent', 'Invoice sent')], max_length=32)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_events', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.package')),
            ],
            options={
                'ordering': ['at', 'id'],
                'indexes': [models.Index(fields=['package', 'at'], name='accounts_pa_package_96babf_idx'), models.Index(fields=['kind', '-at'], name='accounts_pa_kind_8ed35e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['invoice_approved', 'invoice_rejected']), _negated=True), ('actor__isnull', False), _connector='OR'), name='package_event_verdict_has_an_actor')],
            },
        ),
    ]
