# Generated by Django 5.2.17 on 2026-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_backfill_package_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('quoted', 'Quote sent'), ('paid', 'Paid'), ('purchased', 'Products purchased'), ('ready_for_shipping', 'Ready for shipping'), ('in_transit', 'In transit'), ('arrived', 'Arrived at destination'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='quoted', max_length=20),
        ),
    ]
