# Generated by Django 5.2.17 on 2026-09-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_warehouse',
            field=models.BooleanField(default=True),
        ),
    ]
