# Generated by Django 5.2.17 on 2026-09-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_notify_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_warehouse',
            field=models.BooleanField(default=False, help_text='Can scan packages and write intake sheets.', verbose_name='warehouse staff'),
        ),
    ]
