# Generated by Django 5.2.17 on 2026-09-15 08:49
#
# Adds named roles and the finer warehouse workflow. Two data steps:
#
# * Every existing account gets the role its flags already meant. is_staff was
#   the whole back office including role management, so it becomes admin -
#   nobody loses access. is_warehouse alone becomes warehouse.
# * The old "processing" stage is split into measurement and packaging steps;
#   a package that was being processed has not been measured by the new
#   system, so it waits for measurement.

from django.db import migrations, models


def roles_from_flags(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(models.Q(is_staff=True) | models.Q(is_superuser=True)).update(role="admin")
    User.objects.filter(is_warehouse=True, is_staff=False, is_superuser=False).update(
        role="warehouse"
    )


def processing_to_awaiting_measurement(apps, schema_editor):
    Package = apps.get_model("accounts", "Package")
    Package.objects.filter(warehouse_stage="processing").update(
        warehouse_stage="awaiting_measurement"
    )


def awaiting_measurement_to_processing(apps, schema_editor):
    Package = apps.get_model("accounts", "Package")
    Package.objects.filter(
        warehouse_stage__in=["awaiting_measurement", "measured", "awaiting_packaging"]
    ).update(warehouse_stage="processing")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_package_freight'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='warehouse_location',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('office', 'Office worker'), ('warehouse', 'Warehouse worker'), ('driver', 'Driver')], db_index=True, default='customer', max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='warehouse_stage',
            field=models.CharField(choices=[('awaiting_pickup', 'Package expected'), ('received', 'Package received'), ('awaiting_measurement', 'Waiting for measurement'), ('measured', 'Measured'), ('awaiting_packaging', 'Waiting for packaging'), ('packed', 'Packaged'), ('ready', 'Ready for shipping'), ('shipped', 'Shipped')], default='awaiting_pickup', max_length=20),
        ),
        migrations.RunPython(roles_from_flags, migrations.RunPython.noop),
        migrations.RunPython(
            processing_to_awaiting_measurement, awaiting_measurement_to_processing
        ),
    ]
