# Generated by Django 5.2.17 on 2026-09-15 13:03

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_roles_and_warehouse_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=150)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('photo', models.FileField(blank=True, upload_to=accounts.models.delivery_photo_path)),
                ('photo_content_type', models.CharField(blank=True, max_length=20)),
                ('delivered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_confirmation', to='accounts.package')),
            ],
            options={
                'ordering': ['-delivered_at'],
            },
        ),
    ]
