# Generated by Django 5.2.17 on 2026-09-04 12:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_number', models.CharField(blank=True, help_text='Assigned by the office. Left empty on submission.', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('booked_in', 'Booked in'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, help_text='Measured at the counter.', max_digits=8, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Measured at the counter.', max_digits=8, null=True)),
                ('packing_quality', models.CharField(blank=True, choices=[('good', 'Goed'), ('poor', 'Niet goed')], help_text="The office's assessment of the sender's packing, not the sender's.", max_length=10)),
                ('office_notes', models.TextField(blank=True, help_text='Internal. Never shown to the customer.')),
                ('freight', models.CharField(choices=[('sea', 'Zeevracht'), ('air', 'Luchtvracht')], default='sea', max_length=10)),
                ('destination', models.CharField(choices=[('AW', 'Aruba'), ('BQ', 'Bonaire'), ('CW', 'Curaçao'), ('SX', 'Sint Maarten'), ('SR', 'Suriname'), ('other', 'Overig')], max_length=10)),
                ('destination_other', models.CharField(blank=True, max_length=100)),
                ('sender_first_name', models.CharField(max_length=150)),
                ('sender_last_name', models.CharField(max_length=150)),
                ('sender_address', models.CharField(max_length=255)),
                ('sender_postal_code', models.CharField(max_length=20)),
                ('sender_city', models.CharField(max_length=100)),
                ('sender_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, for example +599 9 123 4567.', regex='^\\+?[\\d\\s()-]{7,20}$')])),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipient_first_name', models.CharField(max_length=150)),
                ('recipient_last_name', models.CharField(max_length=150)),
                ('recipient_address', models.CharField(max_length=255)),
                ('recipient_city', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, for example +599 9 123 4567.', regex='^\\+?[\\d\\s()-]{7,20}$')])),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('packing', models.CharField(choices=[('sender', 'Door u'), ('company', 'Door Carib Intertrans')], default='sender', max_length=10)),
                ('payment', models.CharField(choices=[('cash', 'Contant'), ('bank', 'Bank')], default='bank', max_length=10)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit', models.CharField(choices=[('boxes', 'Dozen'), ('pallets', 'Pallets'), ('colli', 'Colli')], default='boxes', max_length=10)),
                ('contents', models.TextField(blank=True)),
                ('contents_attached', models.BooleanField(default=False)),
                ('value_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle', models.CharField(choices=[('na', 'N.v.t.'), ('combustion', 'Benzine/Diesel'), ('electric', 'Elektrisch/Hybride')], default='na', max_length=12)),
                ('emigration', models.BooleanField(default=False)),
                ('id_present', models.BooleanField(default=False)),
                ('deregistered', models.BooleanField(default=False)),
                ('deregistration_present', models.BooleanField(default=False)),
                ('insured', models.BooleanField(default=False)),
                ('insured_value_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text="The sender's own remarks.")),
                ('signature_name', models.CharField(help_text='Typed by the sender in place of a handwritten signature.', max_length=200)),
                ('agreed_terms', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='bookings_bo_status_eb4fb1_idx'), models.Index(fields=['shipping_number'], name='bookings_bo_shippin_d789e2_idx')],
            },
        ),
    ]
