"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_dotenv(path):
    """Read KEY=value lines from a .env file into the environment.

    Kept dependency-free on purpose. Real environment variables always win, so
    this never overrides what a deployment platform has already set.
    """
    if not path.exists():
        return

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        os.environ.setdefault(key.strip(), value.strip().strip("'\""))


load_dotenv(BASE_DIR / ".env")


def env_flag(name, default=False):
    """Read a boolean from the environment. Anything but a truthy word is off."""
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    return [item.strip() for item in os.environ.get(name, default).split(",") if item.strip()]


# DEBUG defaults to off. Forgetting to set it must fail closed, not open.
DEBUG = env_flag("DJANGO_DEBUG", default=False)

# The secret key signs sessions and password-reset tokens. It must never be
# committed. There is a throwaway key for local development only; in
# production a missing key is a hard error rather than a silent weak default.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-local-development-key-not-for-production"
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set when DEBUG is off. "
            "Generate one with: python -c \"from django.core.management.utils "
            'import get_random_secret_key; print(get_random_secret_key())"'
        )

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1" if DEBUG else "")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'corsheaders',

    # Local apps
    'accounts',
    'enquiries',
]

# Must be set before the first migration is applied: Django cannot swap the
# user model cleanly once the auth tables exist.
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Above CommonMiddleware, so it can answer CORS preflight requests.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite by default so a fresh clone runs with no setup. Set the POSTGRES_*
# variables to point at a real database — SQLite locks the whole file on
# write, so it does not survive more than one concurrent user in production.
if os.environ.get("POSTGRES_DB"):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ["POSTGRES_DB"],
            'USER': os.environ.get("POSTGRES_USER", ""),
            'PASSWORD': os.environ.get("POSTGRES_PASSWORD", ""),
            'HOST': os.environ.get("POSTGRES_HOST", "localhost"),
            'PORT': os.environ.get("POSTGRES_PORT", "5432"),
            # Reuse connections rather than opening one per request.
            'CONN_MAX_AGE': 60,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# Password policy
# ---------------------------------------------------------------------------

# 12 characters, matching the signup form in the React app. Length is what
# makes a password hard to guess; composition rules ("one capital, one
# symbol") push people towards predictable shapes like Password1!.
#
# Matched by name, not by list position: indexing breaks silently and
# confusingly if the validator list is ever reordered.
for _validator in AUTH_PASSWORD_VALIDATORS:
    if _validator['NAME'].endswith('MinimumLengthValidator'):
        _validator['OPTIONS'] = {'min_length': 12}
del _validator


# ---------------------------------------------------------------------------
# API
# ---------------------------------------------------------------------------

REST_FRAMEWORK = {
    # Session auth, not tokens: the credential lives in an HttpOnly cookie the
    # browser will not hand to JavaScript, so an XSS bug cannot steal it.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Closed by default. Endpoints that are meant to be public say so
    # explicitly, so forgetting a permission class locks a view rather than
    # exposing it.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Blunt but effective against credential stuffing on login/signup.
        'anon': '60/hour',
        'login': '10/hour',
        # The public contact and quote forms. Generous enough for a real
        # visitor sending a few enquiries, tight enough to make the forms a
        # poor spam target.
        'forms': '20/hour',
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
}


# ---------------------------------------------------------------------------
# CORS and CSRF
# ---------------------------------------------------------------------------

# The Vite dev server runs on a different origin from Django, so the browser
# treats API calls as cross-origin. Only these origins may call the API, and
# only they may send cookies with the request.
CORS_ALLOWED_ORIGINS = env_list(
    "DJANGO_CORS_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173" if DEBUG else "",
)
# Required for the session cookie to be sent at all cross-origin. Note this
# only works with an explicit origin list, never with a wildcard.
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = env_list(
    "DJANGO_CSRF_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173" if DEBUG else "",
)

# The React app has to read this cookie to echo the token back in a header,
# so it cannot be HttpOnly. That is safe: the CSRF token is not a credential.
CSRF_COOKIE_HTTPONLY = False
# 'Lax' would drop the session cookie on cross-origin XHR from the dev server.
CSRF_COOKIE_SAMESITE = 'Lax' if DEBUG else 'None'
SESSION_COOKIE_SAMESITE = 'Lax' if DEBUG else 'None'

# The session cookie is never exposed to JavaScript.
SESSION_COOKIE_HTTPONLY = True


# ---------------------------------------------------------------------------
# Transport security — off in development, mandatory in production
# ---------------------------------------------------------------------------

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Tell browsers to refuse plain HTTP for a year. Start with a small value
    # while testing: this is hard to undo once browsers have cached it.
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", 31536000))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Behind a proxy or load balancer that terminates TLS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# ---------------------------------------------------------------------------
# Uploaded files
# ---------------------------------------------------------------------------

# Where quote attachments are written. Kept outside the static directory: this
# is visitor-supplied content and must never be served as part of the site.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# A request larger than this is rejected before it reaches a view, which caps
# what an upload can cost in memory and disk.
DATA_UPLOAD_MAX_MEMORY_SIZE = 11 * 1024 * 1024   # 11 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024    # spool to disk above 2 MB
