# Generated by Django 5.2.17 on 2026-09-11 11:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_user_notify_warehouse'),
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released to the office')], default='draft', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Whatever is written in the shipment box at the top.', max_length=50)),
                ('pickup', models.BooleanField(default=False, help_text='Ophalen: collected by us rather than dropped off.')),
                ('upper_floor', models.BooleanField(default=False, help_text='Verdieping: the collection is above the ground floor.')),
                ('employees', models.CharField(blank=True, help_text='Werknemers who did the collection.', max_length=255)),
                ('pickup_location', models.CharField(blank=True, max_length=255)),
                ('received_on', models.DateField(blank=True, help_text='Datum aanname goederen - when the goods were taken in.', null=True)),
                ('packing_required', models.BooleanField(default=False, help_text='Inpakken: we pack it.')),
                ('pallet_box', models.BooleanField(default=False, help_text='Palletdoos.')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='aantal kuub (m3)')),
                ('packed_well', models.CharField(blank=True, choices=[('yes', 'Ja'), ('no', 'Nee')], max_length=3)),
                ('damage_present', models.CharField(blank=True, choices=[('yes', 'Ja'), ('no', 'Nee')], max_length=3)),
                ('address_label_present', models.CharField(blank=True, choices=[('yes', 'Ja'), ('no', 'Nee')], max_length=3)),
                ('check_notes', models.TextField(blank=True, help_text='Opmerkingen against the three checks above.')),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('sender', models.CharField(blank=True, max_length=255)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Opmerkingen about the consignment.')),
                ('colli_count', models.PositiveIntegerField(blank=True, help_text='Aantal colli.', null=True)),
                ('packaging', models.CharField(blank=True, choices=[('pallet', 'Pallet'), ('doos', 'Doos'), ('colli', 'Colli'), ('kist', 'Kist'), ('other', 'Anders')], max_length=10)),
                ('packaging_other', models.CharField(blank=True, max_length=100)),
                ('dimensions_weight', models.TextField(blank=True, help_text='Afmetingen & gewicht, as written.')),
                ('freight', models.CharField(blank=True, choices=[('sea', 'Zeevracht'), ('air', 'Luchtvracht')], max_length=10)),
                ('employee_name', models.CharField(blank=True, max_length=150)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_sheets', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_sheets_created', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_sheets', to='accounts.package')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_sheets_released', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'intake sheet',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='warehouse_i_status_20bbf3_idx')],
            },
        ),
    ]
