# Generated by Django 5.2.17 on 2026-09-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakesheet',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
