# Generated by Django 5.2.17 on 2026-09-14 10:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_intakesheet_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('packaging', models.CharField(blank=True, choices=[('pallet', 'Pallet'), ('doos', 'Doos'), ('colli', 'Colli'), ('kist', 'Kist'), ('other', 'Anders')], max_length=10)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='weight per item (kg)')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='warehouse.intakesheet')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
