# Generated by Django 5.2.17 on 2026-09-15 08:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import warehouse.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_roles_and_warehouse_workflow'),
        ('warehouse', '0003_measurement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_type', models.CharField(choices=[('box_damaged', 'Box damaged'), ('contents_damaged', 'Contents damaged'), ('wet_package', 'Wet package'), ('broken_packaging', 'Broken packaging'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('resolution_status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=10)),
                ('resolution_note', models.CharField(blank=True, max_length=500)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='accounts.package')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='damage_reports_resolved', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_reports_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'package_damage_reports',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PackageDamagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=warehouse.models.damage_photo_path)),
                ('content_type', models.CharField(max_length=20)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='warehouse.packagedamagereport')),
            ],
            options={
                'db_table': 'package_damage_photos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PackageMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('5000'))])),
                ('length_cm', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('1500'))])),
                ('width_cm', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('1500'))])),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('1500'))])),
                ('volume_m3', models.DecimalField(decimal_places=4, max_digits=12)),
                ('dimensional_weight_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('measured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_measurements', to='accounts.package')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='warehouse.packagemeasurement')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'package_measurements',
                'ordering': ['-measured_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PackagePackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_type', models.CharField(choices=[('bubble_wrap', 'Bubble wrap'), ('tape', 'Tape'), ('box', 'Box'), ('protection', 'Protection'), ('other', 'Other')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_records', to='accounts.package')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_packaging', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'package_packaging',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PackageActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('package_scanned', 'Package scanned'), ('package_received', 'Package received'), ('measurement_completed', 'Measurement completed'), ('measurement_updated', 'Measurement updated'), ('bubble_wrap_added', 'Bubble wrap added'), ('packaging_added', 'Packaging added'), ('package_packed', 'Package packed'), ('damage_reported', 'Damage reported'), ('damage_resolved', 'Damage resolved'), ('package_marked_ready', 'Package marked ready'), ('package_status_changed', 'Package status changed'), ('location_changed', 'Location changed'), ('problem_reported', 'Problem reported'), ('problem_resolved', 'Problem resolved')], db_index=True, max_length=32)),
                ('description', models.CharField(max_length=500)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='accounts.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'package activity',
                'db_table': 'package_activity',
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['package', 'timestamp'], name='package_act_package_50a98b_idx'), models.Index(fields=['user', '-timestamp'], name='package_act_user_id_caf76f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='packagedamagereport',
            index=models.Index(fields=['package', '-created_at'], name='package_dam_package_b69924_idx'),
        ),
        migrations.AddIndex(
            model_name='packagedamagereport',
            index=models.Index(fields=['resolution_status', '-created_at'], name='package_dam_resolut_4760a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='packagedamagereport',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_status', 'open'), ('resolved_by__isnull', False), _connector='OR'), name='package_damage_resolved_has_resolver'),
        ),
        migrations.AddIndex(
            model_name='packagemeasurement',
            index=models.Index(fields=['package', '-measured_at'], name='package_mea_package_5105f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='packagemeasurement',
            constraint=models.CheckConstraint(condition=models.Q(('weight_kg__gt', 0), ('length_cm__gt', 0), ('width_cm__gt', 0), ('height_cm__gt', 0)), name='package_measurement_positive'),
        ),
        migrations.AddIndex(
            model_name='packagepackaging',
            index=models.Index(fields=['package', '-created_at'], name='package_pac_package_cac467_idx'),
        ),
        migrations.AddConstraint(
            model_name='packagepackaging',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='package_packaging_quantity_positive'),
        ),
    ]
