# Generated by Django 5.2.17 on 2026-09-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_package_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedamagereport',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
