# Generated by Django 5.2.17 on 2026-09-07 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_package_estimated_arrival'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='accounts.package')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The staff member who approved or rejected it.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='invoicing_i_status_b6cdf6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['approved', 'sent']), _negated=True), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='invoice_reviewed_when_approved_or_sent'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False), models.Q(('rejection_reason', ''), _negated=True)), _connector='OR'), name='invoice_rejected_needs_reason'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'sent'), _negated=True), ('sent_at__isnull', False), _connector='OR'), name='invoice_sent_needs_sent_at'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['draft', 'pending_review']), _negated=True), models.Q(('rejection_reason', ''), ('reviewed_at__isnull', True), ('reviewed_by__isnull', True)), _connector='OR'), name='invoice_unreviewed_has_no_verdict')],
            },
        ),
    ]
