# Generated by Django 5.2.17 on 2026-09-07 09:20

import invoicing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_package_estimated_arrival'),
        ('invoicing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, help_text='Rendered on approval. Not written by hand.', upload_to=invoicing.models.invoice_pdf_path),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'sent'), _negated=True), models.Q(('pdf', ''), _negated=True), _connector='OR'), name='invoice_sent_needs_pdf'),
        ),
    ]
