# Generated by Django 5.2.17 on 2026-09-10 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_invoice_created_by_invoice_invoice_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document_content_type',
            field=models.CharField(blank=True, help_text='Always application/pdf today. Stored rather than assumed.', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_filename',
            field=models.CharField(blank=True, help_text='The name the document is offered under. Not its storage path.', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_size',
            field=models.PositiveIntegerField(blank=True, help_text='Size in bytes, recorded when the document was attached.', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Who attached this file. Empty when it was rendered automatically.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_invoice_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
