// Generated by scripts/optimize-images.js — do not edit.
//
// Each export carries a src for browsers that ignore srcSet, the srcSet
// itself, and the intrinsic size. Pass width and height to the <img> as
// well: they are what reserve the space so the page does not jump when
// the photograph arrives.
//
// Regenerate with `npm run images` after changing a source photograph.

import arubaCentraal480 from './Aruba-Centraal-480.webp';
import arubaCentraal540 from './Aruba-Centraal-540.webp';
import bonaireCentraal480 from './Bonaire-centraal-480.webp';
import bonaireCentraal960 from './Bonaire-centraal-960.webp';
import bonaireCentraal1600 from './Bonaire-centraal-1600.webp';
import containerShip480 from './container-ship-480.webp';
import containerShip960 from './container-ship-960.webp';
import containerShip1600 from './container-ship-1600.webp';
import curacaoCentraal480 from './Curacao-centraal-480.webp';
import curacaoCentraal959 from './Curacao-centraal-959.webp';
import portHavenShip480 from './port-haven-ship-480.webp';
import portHavenShip554 from './port-haven-ship-554.webp';
import stMaartenCentraal480 from './St-Maarten-centraal-480.webp';
import stMaartenCentraal768 from './St-Maarten-centraal-768.webp';
import surinameCentraal480 from './Suriname-centraal-480.webp';
import surinameCentraal738 from './Suriname-centraal-738.webp';

/** Aruba-Centraal.jpeg — 540×360 at full size. */
export const arubaCentraal = {
  src: arubaCentraal540,
  srcSet: `${arubaCentraal480} 480w, ${arubaCentraal540} 540w`,
  // For a CSS background, which cannot express a srcset. Use it
  // where the image is painted small, such as a card thumbnail.
  small: arubaCentraal480,
  width: 540,
  height: 360,
};

/** Bonaire-centraal.webp — 1600×900 at full size. */
export const bonaireCentraal = {
  src: bonaireCentraal1600,
  srcSet: `${bonaireCentraal480} 480w, ${bonaireCentraal960} 960w, ${bonaireCentraal1600} 1600w`,
  // For a CSS background, which cannot express a srcset. Use it
  // where the image is painted small, such as a card thumbnail.
  small: bonaireCentraal480,
  width: 1600,
  height: 900,
};

/** container-ship.webp — 1600×900 at full size. */
export const containerShip = {
  src: containerShip1600,
  srcSet: `${containerShip480} 480w, ${containerShip960} 960w, ${containerShip1600} 1600w`,
  // For a CSS background, which cannot express a srcset. Use it
  // where the image is painted small, such as a card thumbnail.
  small: containerShip480,
  width: 1600,
  height: 900,
};

/** Curacao-centraal.png — 959×500 at full size. */
export const curacaoCentraal = {
  src: curacaoCentraal959,
  srcSet: `${curacaoCentraal480} 480w, ${curacaoCentraal959} 959w`,
  // For a CSS background, which cannot express a srcset. Use it
  // where the image is painted small, such as a card thumbnail.
  small: curacaoCentraal480,
  width: 959,
  height: 500,
};

/** port-haven-ship.jpeg — 554×361 at full size. */
export const portHavenShip = {
  src: portHavenShip554,
  srcSet: `${portHavenShip480} 480w, ${portHavenShip554} 554w`,
  // For a CSS background, which cannot express a srcset. Use it
  // where the image is painted small, such as a card thumbnail.
  small: portHavenShip480,
  width: 554,
  height: 361,
};

/** St.Maarten-centraal.webp — 768×576 at full size. */
export const stMaartenCentraal = {
  src: stMaartenCentraal768,
  srcSet: `${stMaartenCentraal480} 480w, ${stMaartenCentraal768} 768w`,
  // For a CSS background, which cannot express a srcset. Use it
  // where the image is painted small, such as a card thumbnail.
  small: stMaartenCentraal480,
  width: 768,
  height: 576,
};

/** Suriname-centraal.jpeg — 738×415 at full size. */
export const surinameCentraal = {
  src: surinameCentraal738,
  srcSet: `${surinameCentraal480} 480w, ${surinameCentraal738} 738w`,
  // For a CSS background, which cannot express a srcset. Use it
  // where the image is painted small, such as a card thumbnail.
  small: surinameCentraal480,
  width: 738,
  height: 415,
};
