// Generated by scripts/optimize-images.js — do not edit.
//
// Each export carries a src for browsers that ignore srcSet, the srcSet
// itself, and the intrinsic size. Pass width and height to the <img> as
// well: they are what reserve the space so the page does not jump when
// the photograph arrives.
//
// Regenerate with `npm run images` after changing a source photograph.

import arubaCentraal480 from './Aruba-centraal-480.webp';
import arubaCentraal960 from './Aruba-centraal-960.webp';
import arubaCentraal1600 from './Aruba-centraal-1600.webp';
import bonaireCentraal480 from './Bonaire-centraal-480.webp';
import bonaireCentraal960 from './Bonaire-centraal-960.webp';
import bonaireCentraal1600 from './Bonaire-centraal-1600.webp';
import boxCart480 from './box-cart-480.webp';
import boxCart960 from './box-cart-960.webp';
import boxCart1600 from './box-cart-1600.webp';
import boxes480 from './boxes-480.webp';
import boxes960 from './boxes-960.webp';
import boxes1024 from './boxes-1024.webp';
import containerShip480 from './container-ship-480.webp';
import containerShip960 from './container-ship-960.webp';
import containerShip1600 from './container-ship-1600.webp';
import curacaoCentraal480 from './Curacao-centraal-480.webp';
import curacaoCentraal960 from './Curacao-centraal-960.webp';
import curacaoCentraal1500 from './Curacao-centraal-1500.webp';
import portHavenShip480 from './port-haven-ship-480.webp';
import portHavenShip554 from './port-haven-ship-554.webp';
import stMaartenCentraal480 from './St-Maarten-centraal-480.webp';
import stMaartenCentraal960 from './St-Maarten-centraal-960.webp';
import stMaartenCentraal1600 from './St-Maarten-centraal-1600.webp';
import surinameCentraal480 from './Suriname-centraal-480.webp';
import surinameCentraal960 from './Suriname-centraal-960.webp';
import surinameCentraal1600 from './Suriname-centraal-1600.webp';

/** Aruba-centraal.avif — 1600×475 at full size. */
export const arubaCentraal = {
  src: arubaCentraal1600,
  srcSet: `${arubaCentraal480} 480w, ${arubaCentraal960} 960w, ${arubaCentraal1600} 1600w`,
  // For a CSS background, which cannot express a srcset. Use it
  // where the image is painted small, such as a card thumbnail.
  small: arubaCentraal480,
  width: 1600,
  height: 475,
};

/** Bonaire-centraal.jpg — 1600×440 at full size. */
export const bonaireCentraal = {
  src: bonaireCentraal1600,
  srcSet: `${bonaireCentraal480} 480w, ${bonaireCentraal960} 960w, ${bonaireCentraal1600} 1600w`,
  // For a CSS background, which cannot express a srcset. Use it
  // where the image is painted small, such as a card thumbnail.
  small: bonaireCentraal480,
  width: 1600,
  height: 440,
};

/** box-cart.jpg — 1600×1200 at full size. */
export const boxCart = {
  src: boxCart1600,
  srcSet: `${boxCart480} 480w, ${boxCart960} 960w, ${boxCart1600} 1600w`,
  // For a CSS background, which cannot express a srcset. Use it
  // where the image is painted small, such as a card thumbnail.
  small: boxCart480,
  width: 1600,
  height: 1200,
};

/** boxes.png — 1024×559 at full size. */
export const boxes = {
  src: boxes1024,
  srcSet: `${boxes480} 480w, ${boxes960} 960w, ${boxes1024} 1024w`,
  // For a CSS background, which cannot express a srcset. Use it
  // where the image is painted small, such as a card thumbnail.
  small: boxes480,
  width: 1024,
  height: 559,
};

/** container-ship.webp — 1600×900 at full size. */
export const containerShip = {
  src: containerShip1600,
  srcSet: `${containerShip480} 480w, ${containerShip960} 960w, ${containerShip1600} 1600w`,
  // For a CSS background, which cannot express a srcset. Use it
  // where the image is painted small, such as a card thumbnail.
  small: containerShip480,
  width: 1600,
  height: 900,
};

/** Curacao-centraal.webp — 1500×500 at full size. */
export const curacaoCentraal = {
  src: curacaoCentraal1500,
  srcSet: `${curacaoCentraal480} 480w, ${curacaoCentraal960} 960w, ${curacaoCentraal1500} 1500w`,
  // For a CSS background, which cannot express a srcset. Use it
  // where the image is painted small, such as a card thumbnail.
  small: curacaoCentraal480,
  width: 1500,
  height: 500,
};

/** port-haven-ship.jpeg — 554×361 at full size. */
export const portHavenShip = {
  src: portHavenShip554,
  srcSet: `${portHavenShip480} 480w, ${portHavenShip554} 554w`,
  // For a CSS background, which cannot express a srcset. Use it
  // where the image is painted small, such as a card thumbnail.
  small: portHavenShip480,
  width: 554,
  height: 361,
};

/** St.Maarten-centraal.avif — 1600×500 at full size. */
export const stMaartenCentraal = {
  src: stMaartenCentraal1600,
  srcSet: `${stMaartenCentraal480} 480w, ${stMaartenCentraal960} 960w, ${stMaartenCentraal1600} 1600w`,
  // For a CSS background, which cannot express a srcset. Use it
  // where the image is painted small, such as a card thumbnail.
  small: stMaartenCentraal480,
  width: 1600,
  height: 500,
};

/** Suriname-centraal.webp — 1600×533 at full size. */
export const surinameCentraal = {
  src: surinameCentraal1600,
  srcSet: `${surinameCentraal480} 480w, ${surinameCentraal960} 960w, ${surinameCentraal1600} 1600w`,
  // For a CSS background, which cannot express a srcset. Use it
  // where the image is painted small, such as a card thumbnail.
  small: surinameCentraal480,
  width: 1600,
  height: 533,
};
